name: Agent Controller 24/7

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  coordinate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests numpy
    
    - name: Run Agent Controller
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python agent_controller.py
