name: Agent Controller 24/7

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  coordinate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found. Installing default dependencies (requests)."
          pip install requests
        fi
    
    - name: Run Agent Controller
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Use GH_PAT for cross-repo permissions
      run: python agent_controller.py
